name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t secure-devsecops-app:v1 ./app

  security-scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t secure-devsecops-app:v1 ./app

      - name: Generate Trivy JSON Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-devsecops-app:v1
          format: json
          output: trivy-report.json

      - name: Generate Trivy Table Report
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-devsecops-app:v1
          format: table
          output: trivy-report.txt

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-reports
          path: |
            trivy-report.json
            trivy-report.txt

      - name: Security Gate
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-devsecops-app:v1
          severity: HIGH,CRITICAL
          exit-code: 0
          format: table

  security-notification:
    runs-on: ubuntu-latest
    needs: security-scan
    if: always() && needs.security-scan.result == 'failure'

    steps:
      - name: Send Email Alert
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}

          subject: "DevSecOps Security Gate Failed"

          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.GMAIL_USERNAME }}

          body: |
            Security Gate Failure Detected

            Repository:
            secure-devsecops-pipeline

            Workflow:
            DevSecOps Pipeline

            Status:
            FAILED

            Severity Threshold:
            HIGH,CRITICAL

            Action Required:
            Review the Trivy report artifact in GitHub Actions.

            Triggered By:
            ${{ github.actor }}

            Commit:
            ${{ github.sha }}
  ecr-push:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t secure-devsecops-app:v1 ./app

      - name: Tag Docker Image
        run: |
          docker tag secure-devsecops-app:v1 \
          637131561898.dkr.ecr.us-east-1.amazonaws.com/secure-devsecops-app:v1

      - name: Push Docker Image to ECR
        run: |
          docker push \
          637131561898.dkr.ecr.us-east-1.amazonaws.com/secure-devsecops-app:v1
  ses-test:
    runs-on: ubuntu-latest
    needs: ecr-push

    steps:
      - name: Send Test Email via AWS SES
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 587
          secure: false

          username: ${{ secrets.SES_SMTP_USERNAME }}
          password: ${{ secrets.SES_SMTP_PASSWORD }}

          subject: "AWS SES Test - Secure DevSecOps Pipeline"

          to: karan.rajawat118@gmail.com
          from: karan.rajawat118@gmail.com

          body: |
            AWS SES integration successful.

            Project:
            Secure DevSecOps Pipeline

            Status:
            SES SMTP Test Passed

            Triggered By:
            ${{ github.actor }}                  